(()=>{'use strict';
const RAW=`first-light|#######/#...o.#/#.....#/#..$..#/#.@...#/#.....#/#######
crossfeed|########/#..oo..#/#......#/#.$.$..#/#...@..#/#......#/########
black-start|########/#.o.o.o#/#......#/#.$.$$.#/#...@..#/#......#/########
split-bus|########/#.o..o.#/#......#/#..##..#/#.$..$.#/#...@..#/#......#/########
relay-bend|########/#..o...#/#....o.#/#..#...#/#.$.$..#/#..@...#/#......#/########
service-loop|#########/#..o.o..#/#.......#/#.#...#.#/#.$.$...#/#...@...#/#.......#/#########
cold-iron|#########/#..o..o.#/#o......#/#...#...#/#.$$.$..#/#...@...#/#.......#/#########
brownout|#########/#..ooo..#/#.......#/#..#.#..#/#.$.$.$.#/#...@...#/#.......#/#########
dead-bus|#########/#..ooo..#/#.#...#.#/#.......#/#.$$.$..#/#....@..#/#.......#/#########
copper-maze|#########/#o..o..o#/#.......#/#.#.#.#.#/#.$.$.$.#/#...@...#/#.......#/#########
backfeed|#########/#o.o....#/#...o...#/#.#...#.#/#.$.$.$.#/#..@....#/#.......#/#########
load-shed|#########/#..o.o..#/#o......#/#..##...#/#.$.$.$.#/#....@..#/#.......#/#########
last-circuit|##########/#..o.oo..#/#....o...#/#..##....#/#.$.$.$..#/#...$@...#/#........#/##########
switchyard|#########/#..oooo.#/#.......#/#.#.#...#/#.$.$.$.#/#..$@...#/#.......#/#########
phase-lock|#########/#o.o.o..#/#.......#/#..###..#/#.$...$.#/#...$@..#/#.......#/#########
auxiliary|##########/#..o.oo..#/#o.......#/#..#..#..#/#.$.$.$..#/#...$@...#/#........#/##########
redline|##########/#o.o..o.o#/#........#/#.#....#.#/#.$.$.$..#/#...$@...#/#........#/##########
island-mode|##########/#..oooo..#/#........#/#..#..#..#/#.$.$.$..#/#..$..@..#/#........#/##########
cascade|##########/#o..oo..o#/#........#/#.#.##.#.#/#.$.$.$..#/#....$@..#/#........#/##########
dawn-sequence|##########/#o..oo..o#/#...##...#/#........#/#.$.$.$..#/#...$@...#/#........#/##########`;
const LEVELS=RAW.split('\n').map((line,index)=>{const [id,data]=line.split('|'),rows=data.split('/'),walls=[],goals=[],crates=[];let player;rows.forEach((row,r)=>[...row].forEach((x,c)=>{const p={row:r,col:c};if(x==='#')walls.push(p);if(x==='o')goals.push(p);if(x==='$')crates.push(p);if(x==='@')player=p}));return{id,index,width:rows[0].length,height:rows.length,walls,goals,crates,player}});
const DIR={up:[-1,0],down:[1,0],left:[0,-1],right:[0,1]},clone=x=>JSON.parse(JSON.stringify(x)),key=p=>p.row+','+p.col,sort=a=>a.slice().sort((x,y)=>x.row-y.row||x.col-y.col);
let revision=0,attempt=0,seed=null,current,history=[],firstInput=false,completionTimer=null;
let prefs={completed:{},bests:{},last:'first-light',sound:true,motion:!matchMedia('(prefers-reduced-motion: reduce)').matches};
try{prefs={...prefs,...JSON.parse(localStorage.getItem('lumen-yard-save')||'{}')}}catch(e){}
const $=s=>document.querySelector(s),yard=$('#yard'),els={name:$('#levelName'),num:$('#levelNumber'),moves:$('#moves'),pushes:$('#pushes'),power:$('#power'),undo:$('#undoBtn'),best:$('#bestLine'),toast:$('#toast'),invite:$('#invitation'),surge:$('#surge'),chapter:$('#chapterLabel')};
function save(){try{localStorage.setItem('lumen-yard-save',JSON.stringify(prefs))}catch(e){}}
function level(id){return LEVELS.find(l=>l.id===id)}
function fresh(id,bump=true){const l=level(id);if(!l)throw err('unknown_level','Unknown board.');if(bump)attempt++;current={levelId:id,player:clone(l.player),crates:clone(l.crates),moveCount:0,pushCount:0,phase:'playing',outcome:null};history=[];prefs.last=id;save()}
function occupied(p,list){return list.some(x=>x.row===p.row&&x.col===p.col)}
function canMove(direction){if(current.phase!=='playing'||!DIR[direction])return false;const l=level(current.levelId),d=DIR[direction],to={row:current.player.row+d[0],col:current.player.col+d[1]};if(occupied(to,l.walls))return false;if(occupied(to,current.crates)){const beyond={row:to.row+d[0],col:to.col+d[1]};return !occupied(beyond,l.walls)&&!occupied(beyond,current.crates)}return true}
function legal(){const a=[];if(current.phase==='playing')for(const direction of Object.keys(DIR))if(canMove(direction))a.push({type:'move',direction});if(history.length)a.push({type:'undo'});for(const l of LEVELS)if(l.id!==current.levelId)a.push({type:'select_level',levelId:l.id});return a}
function snapshot(){const l=level(current.levelId),powered=current.crates.filter(c=>occupied(c,l.goals)).length;return{revision,attempt,phase:current.phase,outcome:current.outcome,levelId:current.levelId,width:l.width,height:l.height,walls:sort(clone(l.walls)),goals:sort(clone(l.goals)),crates:sort(clone(current.crates)),player:clone(current.player),poweredGoals:powered,moveCount:current.moveCount,pushCount:current.pushCount,undoAvailable:history.length>0,legalActions:legal()}}
function err(code,message){const e=new Error(message);e.code=code;return e}
function equalAction(a,b){return JSON.stringify(a)===JSON.stringify(b)}
function mutate(action,source='api'){
 if(!action||typeof action!=='object')throw err('invalid_action','Malformed action.');
 if(action.type==='move'){
  if(current.phase==='complete')throw err('phase_complete','Movement is frozen after completion.');
  if(!DIR[action.direction])throw err('invalid_action','Unknown direction.');
  if(!canMove(action.direction)){if(source==='human'){feedback('PATH BLOCKED');sound('blocked')}throw err('illegal_action','That move is blocked.');}
  history.push(clone(current));const d=DIR[action.direction],to={row:current.player.row+d[0],col:current.player.col+d[1]},ci=current.crates.findIndex(c=>key(c)===key(to));current.player=to;current.moveCount++;
  if(ci>=0){current.crates[ci]={row:to.row+d[0],col:to.col+d[1]};current.pushCount++;sound(occupied(current.crates[ci],level(current.levelId).goals)?'socket':'push')}else sound('step');
  const l=level(current.levelId);if(current.crates.every(c=>occupied(c,l.goals))){current.phase='complete';current.outcome='powered';const prev=prefs.bests[current.levelId];prefs.completed[current.levelId]=true;prefs.bests[current.levelId]=prev==null?current.moveCount:Math.min(prev,current.moveCount);save()}
 }else if(action.type==='undo'){
  if(!history.length)throw err('illegal_action','Nothing to undo.');current=history.pop();sound('undo');
 }else if(action.type==='select_level'){
  if(!level(action.levelId))throw err('unknown_level','Unknown board.');if(action.levelId===current.levelId)throw err('duplicate_action','That board is already selected.');fresh(action.levelId);
 }else throw err('invalid_action','Unknown action type.');
 revision++;firstInput=true;render();return snapshot();
}
function act(action){return mutate(clone(action),'api')}
function restart(){fresh(current.levelId);revision++;firstInput=true;render();return snapshot()}
function reset(s){seed=s;revision=0;attempt=0;fresh('first-light');firstInput=false;render();return snapshot()}
window.__ARENA_GAME__={reset,snapshot,act,restart};
function fit(){const l=level(current.levelId),wrap=$('#yardWrap'),maxW=wrap.clientWidth-12,maxH=wrap.clientHeight-12;document.documentElement.style.setProperty('--tile',Math.max(25,Math.floor(Math.min(maxW/l.width,maxH/l.height,64)))+'px')}
function render(){const l=level(current.levelId),s=snapshot();yard.style.gridTemplateColumns=`repeat(${l.width},var(--tile))`;yard.style.gridTemplateRows=`repeat(${l.height},var(--tile))`;yard.innerHTML='';
 for(let r=0;r<l.height;r++)for(let c=0;c<l.width;c++){const p={row:r,col:c},t=document.createElement('div');t.className='tile '+(occupied(p,l.walls)?'wall':'floor')+(occupied(p,l.goals)?' goal':'')+(occupied(p,l.goals)&&occupied(p,current.crates)?' powered':'');t.dataset.row=r;t.dataset.col=c;yard.appendChild(t)}
 current.crates.forEach(c=>{const e=document.createElement('div');e.className='entity crate'+(occupied(c,l.goals)?' powered':'');e.style.transform=`translate(${c.col}00%,${c.row}00%)`;yard.appendChild(e)});
 const p=document.createElement('div');p.className='entity robot';p.dataset.dir=window.lastDir||'up';p.style.transform=`translate(${current.player.col}00%,${current.player.row}00%)`;yard.appendChild(p);
 els.name.textContent=l.id.replaceAll('-',' ').toUpperCase();els.num.textContent=`CIRCUIT ${String(l.index+1).padStart(2,'0')}`;els.moves.textContent=s.moveCount;els.pushes.textContent=s.pushCount;els.power.textContent=`${s.poweredGoals}/${l.goals.length}`;els.undo.disabled=!s.undoAvailable;els.invite.classList.toggle('gone',firstInput||current.levelId!=='first-light');els.chapter.textContent=l.index<3?'OPENING RESTORATION':l.index===19?'FINAL DAWN':'NIGHT SHIFT';
 const best=prefs.bests[l.id];els.best.textContent=best==null?'No best yet — wake this circuit.':`Best: ${best} moves${s.phase==='playing'?' · Beat the record.':''}`;$('#yardWrap').classList.toggle('yard-complete',s.phase==='complete');renderMap();requestAnimationFrame(fit);
 clearTimeout(completionTimer);if(s.phase==='complete'){els.surge.classList.remove('active');void els.surge.offsetWidth;els.surge.classList.add('active');sound('complete');completionTimer=setTimeout(showCompletion,prefs.motion?650:50)}
}
function feedback(msg){els.toast.textContent=msg;els.toast.classList.add('show');yard.classList.remove('blocked');void yard.offsetWidth;yard.classList.add('blocked');clearTimeout(feedback.t);feedback.t=setTimeout(()=>els.toast.classList.remove('show'),700)}
let audio;
function sound(type){if(!prefs.sound||!firstInput&&type!=='step'&&type!=='push'&&type!=='socket')return;try{audio||(audio=new AudioContext);const o=audio.createOscillator(),g=audio.createGain(),now=audio.currentTime,sets={step:[180,.035,.035],push:[75,.12,.09],socket:[420,.18,.12],blocked:[90,.05,.05],undo:[260,.14,.06],complete:[130,.7,.16]}[type]||[200,.05,.03];o.type=type==='push'?'square':'sine';o.frequency.setValueAtTime(sets[0],now);if(type==='complete')o.frequency.exponentialRampToValueAtTime(700,now+sets[1]);if(type==='undo')o.frequency.exponentialRampToValueAtTime(110,now+sets[1]);g.gain.setValueAtTime(sets[2],now);g.gain.exponentialRampToValueAtTime(.001,now+sets[1]);o.connect(g).connect(audio.destination);o.start();o.stop(now+sets[1])}catch(e){}}
function humanMove(direction){window.lastDir=direction;firstInput=true;try{mutate({type:'move',direction},'human')}catch(e){}}
function renderMap(){const grid=$('#mapGrid');grid.innerHTML='';LEVELS.forEach(l=>{const b=document.createElement('button');b.className='map-card'+(l.id===current.levelId?' current':'')+(prefs.completed[l.id]?' complete':'');b.innerHTML=`<span>${String(l.index+1).padStart(2,'0')}</span><b>${l.id.replaceAll('-',' ').toUpperCase()}</b><em>${prefs.bests[l.id]!=null?'BEST '+prefs.bests[l.id]+' MOVES':prefs.completed[l.id]?'RESTORED':'SLEEPING'}</em>`;b.onclick=()=>{if(l.id!==current.levelId){mutate({type:'select_level',levelId:l.id},'human')}closePanels()};grid.appendChild(b)})}
function openPanel(id){$('#scrim').hidden=false;document.querySelectorAll('.panel').forEach(p=>p.hidden=true);$(id).hidden=false;setTimeout(()=>$(id).querySelector('button')?.focus(),0)}function closePanels(){document.querySelectorAll('.panel').forEach(p=>p.hidden=true);$('#scrim').hidden=true}
function showCompletion(){const l=level(current.levelId),all=LEVELS.every(x=>prefs.completed[x.id]),chapter=l.index===2,final=l.index===19&&all,early=l.index===19&&!all,p=$('#completePanel');$('#completeKicker').textContent=final?'THE YARD AWAKES':chapter?'OPENING RESTORED':'CIRCUIT ONLINE';$('#completeTitle').textContent=final?'DAWN SEQUENCE':chapter?'GRID RESTORED':l.id.replaceAll('-',' ').toUpperCase();$('#completeCopy').textContent=final?'Every circuit sings. Greenhouse glass catches the first sun. Good work, yard crew.':chapter?'Three lines are alive. The deeper yard is ready for your hands.':early?'This circuit shines, but unfinished lines still wait in the yard.':'Relay seated. Current is holding steady.';$('#summary').hidden=!final;if(final){const total=LEVELS.reduce((n,x)=>n+(prefs.bests[x.id]||0),0);$('#summary').innerHTML=`<div><b>20/20</b><span>Restored</span></div><div><b>${total}</b><span>Best moves</span></div>`}$('#nextBtn').textContent=final?'Replay First Light':early?'Find Unfinished':l.index===LEVELS.length-1?'Board Map':'Next Circuit';openPanel('#completePanel')}
$('#undoBtn').onclick=()=>{try{mutate({type:'undo'},'human')}catch(e){}};$('#restartBtn').onclick=()=>restart();document.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>humanMove(b.dataset.dir));$('#mapBtn').onclick=$('#brand').onclick=()=>openPanel('#mapPanel');$('#settingsBtn').onclick=()=>openPanel('#settingsPanel');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closePanels);$('#scrim').onclick=closePanels;$('#completeMapBtn').onclick=()=>openPanel('#mapPanel');$('#replayBtn').onclick=()=>{closePanels();restart()};$('#nextBtn').onclick=()=>{const i=level(current.levelId).index,all=LEVELS.every(x=>prefs.completed[x.id]);closePanels();if(i===19&&!all)return openPanel('#mapPanel');const id=LEVELS[i===19?0:i+1].id;mutate({type:'select_level',levelId:id},'human')};
function toggle(k,el){prefs[k]=!prefs[k];el.setAttribute('aria-checked',prefs[k]);el.textContent=prefs[k]?'ON':'OFF';if(k==='motion')document.documentElement.style.setProperty('--motion',prefs[k]?1:0);save()}$('#soundToggle').onclick=()=>toggle('sound',$('#soundToggle'));$('#motionToggle').onclick=()=>toggle('motion',$('#motionToggle'));
let touch;yard.addEventListener('pointerdown',e=>{touch={x:e.clientX,y:e.clientY};yard.setPointerCapture(e.pointerId)});yard.addEventListener('pointerup',e=>{if(!touch)return;const dx=e.clientX-touch.x,dy=e.clientY-touch.y;if(Math.hypot(dx,dy)>22)humanMove(Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up');else{const t=e.target.closest('.tile');if(t){const dr=+t.dataset.row-current.player.row,dc=+t.dataset.col-current.player.col;if(Math.abs(dr)+Math.abs(dc)===1)humanMove(dr<0?'up':dr>0?'down':dc<0?'left':'right')}}touch=null});
addEventListener('keydown',e=>{if(!$('#scrim').hidden&&e.key==='Escape')return closePanels();const m={ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right'}[e.key];if(m){e.preventDefault();humanMove(m)}else if(['u','U','Backspace'].includes(e.key)){e.preventDefault();try{mutate({type:'undo'},'human')}catch(x){}}else if(['r','R'].includes(e.key))restart()});addEventListener('resize',fit);
let gpPrev={};function gamepads(){const gp=navigator.getGamepads?.()[0];if(gp){const now={up:gp.buttons[12]?.pressed||gp.axes[1]<-.6,down:gp.buttons[13]?.pressed||gp.axes[1]>.6,left:gp.buttons[14]?.pressed||gp.axes[0]<-.6,right:gp.buttons[15]?.pressed||gp.axes[0]>.6,primary:gp.buttons[0]?.pressed,undo:gp.buttons[1]?.pressed,start:gp.buttons[9]?.pressed};for(const d of ['up','down','left','right'])if(now[d]&&!gpPrev[d])humanMove(d);if(now.primary&&!gpPrev.primary&&document.activeElement?.click)document.activeElement.click();if(now.undo&&!gpPrev.undo)try{mutate({type:'undo'},'human')}catch(e){}if(now.start&&!gpPrev.start)restart();gpPrev=now}requestAnimationFrame(gamepads)}requestAnimationFrame(gamepads);
function response(port,msg,accepted,error){port.postMessage({protocol:'arena.game.v1',type:'response',requestId:msg.requestId,sessionId:msg.sessionId,generation:msg.generation,accepted,revision,state:snapshot(),...(error?{error:{code:error.code||'error',message:error.message}}:{})})}
addEventListener('message',e=>{const m=e.data;if(e.source!==parent||!m||m.protocol!=='arena.game.v1'||m.type!=='connect'||typeof m.sessionId!=='string'||!Number.isInteger(m.generation)||e.ports.length!==1)return;const port=e.ports[0],sid=m.sessionId,gen=m.generation,requests=new Set();port.onmessage=ev=>{const q=ev.data;if(!q||q.protocol!=='arena.game.v1'||q.sessionId!==sid||q.generation!==gen)return;try{if(q.requestId==null)throw err('invalid_request','Request ID is required.');if(requests.has(q.requestId))throw err('duplicate_action','Duplicate request.');requests.add(q.requestId);if(q.command==='observe')return response(port,q,true);if(!Number.isInteger(q.expectedRevision))throw err('expected_revision','Expected revision is required.');if(q.expectedRevision!==revision)throw err('stale_revision','Revision does not match.');if(q.command==='act')mutate(q.action,'arena');else if(q.command==='restart')restart();else throw err('unknown_command','Unknown command.');requestAnimationFrame(()=>response(port,q,true))}catch(x){response(port,q,false,x)}};port.start();port.postMessage({protocol:'arena.game.v1',type:'ready',sessionId:sid,generation:gen,accepted:true,revision,state:snapshot()})});
current=null;fresh(prefs.last&&level(prefs.last)?prefs.last:'first-light');$('#soundToggle').setAttribute('aria-checked',prefs.sound);$('#soundToggle').textContent=prefs.sound?'ON':'OFF';$('#motionToggle').setAttribute('aria-checked',prefs.motion);$('#motionToggle').textContent=prefs.motion?'ON':'OFF';document.documentElement.style.setProperty('--motion',prefs.motion?1:0);render();
})();
