(()=>{'use strict';
const STEP=1000/60,RANKS=['DRIFTWOOD','SEA GLASS','MOON PEARL','TIDEKEEPER','DEEP STAR'],MAX_EVENTS=240;
const $=s=>document.querySelector(s), boardEl=$('#board'), gameEl=$('#game'), ceremony=$('#ceremony');
let sessionBest=0,attempt=0,revision=0,state,accumulator=0,rafLast=performance.now(),audio=null,portBinding=null,renderedRevision=-1;
function hashString(v){let h=2166136261;for(const c of String(v)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function mix(a){a|=0;a=Math.imul(a^(a>>>16),0x45d9f3b);a=Math.imul(a^(a>>>16),0x45d9f3b);return(a^(a>>>16))>>>0}
function rand(seed,i){return mix((seed^Math.imul(i+1,0x9e3779b1))>>>0)/4294967296}
function config(pool){let w=Math.min(8,5+Math.floor((pool-1)/2)),h=Math.min(9,6+Math.floor(pool/3)),mines=Math.min(w*h-12,4+pool*2);return{w,h,mines,duration:Math.max(38,76+pool*7)}}
function neighbors(i,w,h){let a=[],x=i%w,y=(i/w)|0;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){let nx=x+dx,ny=y+dy;if((dx||dy)&&nx>=0&&ny>=0&&nx<w&&ny<h)a.push(ny*w+nx)}return a}
function countsFor(mines,w,h){return Array.from({length:w*h},(_,i)=>neighbors(i,w,h).reduce((n,j)=>n+(mines[j]?1:0),0))}
function solverValid(mines,counts,w,h,first){let open=new Set(),flag=new Set();function flood(start){let q=[start];while(q.length){let i=q.shift();if(open.has(i)||flag.has(i)||mines[i])continue;open.add(i);if(counts[i]===0)neighbors(i,w,h).forEach(n=>q.push(n))}}flood(first);let changed=true;while(changed){changed=false;for(const i of [...open]){let ns=neighbors(i,w,h),covered=ns.filter(n=>!open.has(n)&&!flag.has(n)),f=ns.filter(n=>flag.has(n)).length;if(covered.length&&counts[i]-f===covered.length){covered.forEach(n=>flag.add(n));changed=true}if(covered.length&&counts[i]===f){covered.forEach(n=>flood(n));changed=true}}let unknown=[];for(let i=0;i<w*h;i++)if(!open.has(i)&&!flag.has(i))unknown.push(i);if(unknown.length&&mines.filter(Boolean).length-flag.size===unknown.length){unknown.forEach(i=>flag.add(i));changed=true}}
return open.size===w*h-mines.filter(Boolean).length}
function generate(pool,first){let c=config(pool),safe=new Set([first,...neighbors(first,c.w,c.h)]),seed=mix(state.seedHash^Math.imul(pool,0x85ebca6b)^Math.imul(first+1,0xc2b2ae35));for(let pass=0;pass<500;pass++){let candidates=[];for(let i=0;i<c.w*c.h;i++)if(!safe.has(i))candidates.push(i);candidates.sort((a,b)=>rand(seed+pass*977,a)-rand(seed+pass*977,b));let mines=Array(c.w*c.h).fill(false);candidates.slice(0,c.mines).forEach(i=>mines[i]=true);let counts=countsFor(mines,c.w,c.h);if(solverValid(mines,counts,c.w,c.h,first))return{mines,counts}}
// Deterministic fallback: sparse mines beyond the guaranteed quiet opening; deduction validation above normally succeeds.
let candidates=[];for(let i=0;i<c.w*c.h;i++)if(!safe.has(i))candidates.push(i);let mines=Array(c.w*c.h).fill(false);candidates.sort((a,b)=>rand(seed,a)-rand(seed,b)).slice(0,c.mines).forEach(i=>mines[i]=true);return{mines,counts:countsFor(mines,c.w,c.h)}}
function freshPool(pool){let c=config(pool);state.phase='ready';state.pool=pool;state.w=c.w;state.h=c.h;state.urchins=c.mines;state.duration=c.duration;state.poolTicks=0;state.first=false;state.mines=null;state.counts=null;state.open=Array(c.w*c.h).fill(false);state.flags=Array(c.w*c.h).fill(false);state.stung=null;state.poolStartTick=state.tick;state.openedThisPool=0}
function reset(seed='shoal'){attempt++;revision=0;accumulator=0;state={seed:String(seed),seedHash:hashString(seed),phase:'ready',tick:0,pearls:0,moves:0,events:[],seq:0,deepest:1,biggestRipple:0,fastest:null,rank:null};freshPool(1);render(true);return snapshot()}
function event(kind,extra={}){let e={seq:++state.seq,kind,tick:state.tick,...extra};state.events.push(e);if(state.events.length>MAX_EVENTS)state.events.shift();return e}
function flood(start){let opened=[],q=[start],seen=new Set();while(q.length){let i=q.shift();if(seen.has(i)){continue}seen.add(i);if(state.open[i]||state.flags[i]||state.mines[i])continue;state.open[i]=true;opened.push(i);if(state.counts[i]===0)neighbors(i,state.w,state.h).forEach(n=>q.push(n))}return opened}
function endRun(fatal){state.phase='ended';state.stung=fatal;event('sting');state.rank=rankFor(state.pearls);sessionBest=Math.max(sessionBest,state.pearls);event('run_end');sound('sting');render();setTimeout(()=>showCeremony(),650)}
function clearCheck(){let safe=state.w*state.h-state.urchins;if(state.open.filter(Boolean).length!==safe)return false;let tide=Math.max(0,1-state.poolTicks/(state.duration*60)),bonus=Math.round((28+state.pool*24)*tide*state.pool),cleared=state.pool;state.pearls+=bonus;state.fastest=state.fastest==null?state.poolTicks:Math.min(state.fastest,state.poolTicks);event('pool_clear',{pool:cleared});state.deepest=cleared;freshPool(cleared+1);state.deepest=state.pool;sound('clear');hostReact('happy');showToast(`Pool ${cleared} clear  +${bonus}`);render(true);return true}
function validate(action){if(!action||typeof action!=='object'||!['open','flag','unflag','sweep'].includes(action.type))return'bad_action';if(state.phase==='ended')return'run_ended';let{x,y}=action;if(!Number.isInteger(x)||!Number.isInteger(y)||x<0||y<0||x>=state.w||y>=state.h)return'out_of_bounds';let i=y*state.w+x;if(action.type==='open'&&(state.open[i]||state.flags[i]))return'illegal_open';if(action.type==='flag'&&(state.open[i]||state.flags[i]))return'illegal_flag';if(action.type==='unflag'&&!state.flags[i])return'illegal_unflag';if(action.type==='sweep'){if(!state.open[i])return'illegal_sweep';let ns=neighbors(i,state.w,state.h),fc=ns.filter(n=>state.flags[n]).length;if(fc!==state.counts[i]||!ns.some(n=>!state.open[n]&&!state.flags[n]))return'illegal_sweep'}return null}
function mutate(action){let error=validate(action);if(error)return{accepted:false,error,state:snapshot()};ensureAudio();let i=action.y*state.w+action.x;if(!state.first&&(action.type==='flag'||action.type==='unflag')){}else if(!state.first){let g=generate(state.pool,i);state.mines=g.mines;state.counts=g.counts;state.first=true;state.phase='playing'}
state.moves++;let opened=[];
if(action.type==='flag'){state.flags[i]=true;event('flag');sound('flag')}
if(action.type==='unflag'){state.flags[i]=false;event('unflag');sound('flag')}
if(action.type==='open'){if(state.mines[i]){event('open',{opened:0});revision++;endRun({x:action.x,y:action.y});return{accepted:true,state:snapshot()}}opened=flood(i);state.pearls+=opened.length*state.pool;state.openedThisPool+=opened.length;state.biggestRipple=Math.max(state.biggestRipple,opened.length);event('open',{opened:opened.length});sound(opened.length>1?'ripple':'open')}
if(action.type==='sweep'){let targets=neighbors(i,state.w,state.h).filter(n=>!state.open[n]&&!state.flags[n]);let fatal=targets.find(n=>state.mines[n]);if(fatal!==undefined){for(const n of targets){if(n===fatal)break;if(!state.mines[n])opened.push(...flood(n))}state.pearls+=opened.length*state.pool;event('sweep',{opened:opened.length});revision++;endRun({x:fatal%state.w,y:(fatal/state.w)|0});return{accepted:true,state:snapshot()}}targets.forEach(n=>opened.push(...flood(n)));state.pearls+=opened.length*state.pool;state.openedThisPool+=opened.length;state.biggestRipple=Math.max(state.biggestRipple,opened.length);event('sweep',{opened:opened.length});sound('sweep')}
revision++;render();if(opened.length>1){gameEl.classList.add('ripple');hostReact('happy');setTimeout(()=>gameEl.classList.remove('ripple'),380)}clearCheck();return{accepted:true,state:snapshot()}}
function act(action){return mutate(action).state}
function advance(ms){if(!Number.isFinite(ms)||ms<=0)return snapshot();if(state.phase!=='playing')return snapshot();accumulator+=ms;let steps=Math.floor((accumulator+1e-7)/STEP);accumulator-=steps*STEP;state.tick+=steps;state.poolTicks+=steps;renderHud();return snapshot()}
function rankFor(p){return RANKS[p>=2200?4:p>=1000?3:p>=420?2:p>=140?1:0]}
function rows(){let out=[];for(let y=0;y<state.h;y++){let row='';for(let x=0;x<state.w;x++){let i=y*state.w+x;if(state.phase==='ended'){if(state.stung&&state.stung.x===x&&state.stung.y===y)row+='X';else if(state.flags[i])row+=state.mines[i]?'+':'-';else if(state.mines[i])row+='*';else if(state.open[i])row+=state.counts[i];else row+='#'}else if(state.flags[i])row+='F';else if(state.open[i])row+=state.counts[i];else row+='#'}out.push(row)}return out}
function snapshot(includeEvents=true){let s={phase:state.phase,tick:state.tick,elapsedMs:Math.round(state.tick*STEP*1000)/1000,seed:state.seed,attempt,revision,pool:state.pool,pearls:state.pearls,sessionBest,moves:state.moves,rank:state.rank,rankLadder:[...RANKS],gridWidth:state.w,gridHeight:state.h,urchinsTotal:state.urchins,flagsPlaced:state.flags.filter(Boolean).length,urchinsLeft:state.urchins-state.flags.filter(Boolean).length,tideFraction:state.first?Math.max(0,1-state.poolTicks/(state.duration*60)):1,firstTurnDone:state.first,stungAt:state.stung?{...state.stung}:null,rows:rows()};if(includeEvents){s.events=state.events.map(e=>({...e}));s.lastEvent=s.events.length?{...s.events[s.events.length-1]}:null}return deepFreeze(s)}
function deepFreeze(o){Object.values(o).forEach(v=>v&&typeof v==='object'&&!Object.isFrozen(v)&&deepFreeze(v));return Object.freeze(o)}
function render(force=false){let rs=rows();if(force||boardEl.children.length!==state.w*state.h){boardEl.innerHTML='';boardEl.style.setProperty('--cols',state.w);boardEl.style.setProperty('--rows',state.h);for(let i=0;i<state.w*state.h;i++){let b=document.createElement('button');b.className='cell';b.dataset.i=i;b.setAttribute('role','gridcell');b.style.setProperty('--rot',`${((i*47)%17)-8}deg`);b.innerHTML='<span class="shell"></span><span class="number"></span><span class="flag-mark"></span><span class="urchin-mark"></span>';boardEl.appendChild(b)}}rs.join('').split('').forEach((c,i)=>{let el=boardEl.children[i],n=el.querySelector('.number');el.className='cell';n.textContent='';if(/[0-8]/.test(c)){el.classList.add('open');n.textContent=c;n.className=`number n${c}`}if(c==='F'||c==='+'||c==='-')el.classList.add('flag');if(c==='*'||c==='X'||c==='+')el.classList.add('urchin');if(c==='X')el.classList.add('fatal');if(c==='-')el.classList.add('wrong');el.setAttribute('aria-label',c==='#'?'Covered shell':c==='F'?'Pennanted shell':/[0-8]/.test(c)?`Open shell, ${c} nearby urchins`:c==='X'?'Fatal urchin':'Revealed shell')});renderHud();renderedRevision=revision}
function renderHud(){let s=snapshot(false);$('#pearls').textContent=s.pearls;$('#left').textContent=s.urchinsLeft;$('#poolLabel').textContent=`POOL ${s.pool}`;$('#tide').style.transform=`scaleX(${s.tideFraction})`;$('#hint').textContent=!s.firstTurnDone?'Tap a shell to begin':s.phase==='ended'?'Study where the logic broke':s.urchinsLeft<=2?'The counter is a clue':s.moves<3?'Hold a shell to plant a pennant':'Tap a satisfied number to sweep';$('#host').className='host '+(s.phase==='ended'?'stung':s.rows.join('').replace(/[F0-8]/g,'').length<=s.urchinsTotal+4?'hold':'calm')}
function showToast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1100)}function hostReact(c){let h=$('#host');h.className='host '+c;setTimeout(()=>renderHud(),850)}
function showCeremony(){if(state.phase!=='ended')return;$('#rank').textContent=state.rank;$('#finalPearls').textContent=state.pearls;$('#best').textContent=sessionBest;$('#story').textContent=`Deepest pool ${state.deepest} · Biggest ripple ${state.biggestRipple} shells`;$('#ladder').innerHTML=RANKS.map(r=>`<span class="grade ${r===state.rank?'earned':''}">${r}</span>`).join('');ceremony.hidden=false}
function restart(){ceremony.hidden=true;return reset(state.seed)}
let holdTimer=null,holdFired=false,startX=0,startY=0;
boardEl.addEventListener('pointerdown',e=>{let cell=e.target.closest('.cell');if(!cell||state.phase==='ended')return;e.preventDefault();holdFired=false;startX=e.clientX;startY=e.clientY;cell.setPointerCapture?.(e.pointerId);holdTimer=setTimeout(()=>{let i=+cell.dataset.i,x=i%state.w,y=(i/state.w)|0,r=mutate({type:state.flags[i]?'unflag':'flag',x,y});holdFired=r.accepted;navigator.vibrate?.(20)},480)});
boardEl.addEventListener('pointermove',e=>{if(Math.hypot(e.clientX-startX,e.clientY-startY)>12){clearTimeout(holdTimer);holdTimer=null}});
boardEl.addEventListener('pointerup',e=>{clearTimeout(holdTimer);holdTimer=null;let cell=e.target.closest('.cell');if(!cell||holdFired)return;let i=+cell.dataset.i,x=i%state.w,y=(i/state.w)|0;mutate({type:state.open[i]?'sweep':'open',x,y})});
boardEl.addEventListener('pointercancel',()=>clearTimeout(holdTimer));boardEl.addEventListener('contextmenu',e=>{e.preventDefault();let cell=e.target.closest('.cell');if(!cell)return;clearTimeout(holdTimer);holdFired=true;let i=+cell.dataset.i,x=i%state.w,y=(i/state.w)|0;mutate({type:state.flags[i]?'unflag':'flag',x,y})});
ceremony.addEventListener('click',restart);document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='r')restart()});
function ensureAudio(){if(audio)return;let AudioCtor=window.AudioContext||window.webkitAudioContext;if(!AudioCtor){audio={silent:true};return}try{audio=new AudioCtor()}catch(_){audio={silent:true}}}
function tone(freq,dur=.08,delay=0,type='sine',gain=.035){if(!audio||audio.silent)return;let o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(gain,t+.01);g.gain.exponentialRampToValueAtTime(.001,t+dur);o.connect(g).connect(audio.destination);o.start(t);o.stop(t+dur+.02)}
function sound(k){if(!audio)return;if(k==='flag')tone(520,.06,0,'square',.025);if(k==='open')tone(310,.09);if(k==='ripple')for(let i=0;i<6;i++)tone(280+i*45,.1,i*.035,'sine',.025);if(k==='sweep')for(let i=0;i<4;i++)tone(400+i*80,.08,i*.025,'triangle',.03);if(k==='sting'){tone(120,.45,0,'sawtooth',.06);gameEl.classList.add('shake');setTimeout(()=>gameEl.classList.remove('shake'),450);navigator.vibrate?.([40,30,90])}if(k==='clear')for(let i=0;i<4;i++)tone([330,440,550,660][i],.2,i*.09,'sine',.04)}
function loop(now){let dt=Math.min(100,now-rafLast);rafLast=now;if(state?.phase==='playing')advance(dt);requestAnimationFrame(loop)}
function bridgeState(){let s=snapshot(false);return s}
function sendResponse(p,msg,accepted,error){p.postMessage({protocol:'arena.game.v1',type:'response',requestId:msg.requestId,sessionId:portBinding.sessionId,generation:portBinding.generation,accepted,revision,state:bridgeState(),...(error?{error}:{})})}
window.addEventListener('message',e=>{let m=e.data;if(e.source!==parent||!m||m.protocol!=='arena.game.v1'||m.type!=='connect'||typeof m.sessionId!=='string'||!Number.isInteger(m.generation)||!e.ports?.[0])return;if(portBinding)portBinding.port.close();let p=e.ports[0];portBinding={port:p,sessionId:m.sessionId,generation:m.generation};p.onmessage=ev=>{let q=ev.data;if(!q||q.protocol!=='arena.game.v1'||q.sessionId!==portBinding.sessionId||q.generation!==portBinding.generation)return;if(!['observe','act','restart'].includes(q.command))return sendResponse(p,q,false,{code:'bad_command',message:'Unknown command'});if(q.command==='observe')return sendResponse(p,q,true);if(!Number.isInteger(q.expectedRevision)||q.expectedRevision!==revision)return sendResponse(p,q,false,{code:'stale_revision',message:'Revision does not match'});if(q.command==='restart'){restart();return requestAnimationFrame(()=>sendResponse(p,q,true))}let result=mutate(q.action);if(!result.accepted)return sendResponse(p,q,false,{code:result.error,message:'Illegal action'});requestAnimationFrame(()=>sendResponse(p,q,true))};p.start?.();p.postMessage({protocol:'arena.game.v1',type:'ready',sessionId:m.sessionId,generation:m.generation,accepted:true,revision,state:bridgeState()})});
window.__ARENA_GAME__={reset,snapshot,act,restart,advance};reset('shoal');requestAnimationFrame(loop);
})();
