/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=runtime/wrangler.artifact.jsonc --include-runtime=false --env-interface=RuntimeArtifactBindings runtime/artifact-bindings.generated.d.ts` (hash: bed9d9fe54f48f69cfd4334cf11e8d0e)
interface __BaseEnv_RuntimeArtifactBindings {
	ASSETS: Fetcher;
	PUBLIC_RELEASE: "true";
	MAIN_ORIGIN: "http://127.0.0.1:8787";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/artifact");
	}
	interface Env extends __BaseEnv_RuntimeArtifactBindings {}
}
interface RuntimeArtifactBindings extends __BaseEnv_RuntimeArtifactBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_RELEASE" | "MAIN_ORIGIN">> {}
}
