/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=runtime/wrangler.main.jsonc --include-runtime=false --env-interface=RuntimeMainBindings runtime/main-bindings.generated.d.ts` (hash: c8066d3403e26fbdd65869c763ae9b69)
interface __BaseEnv_RuntimeMainBindings {
	DB: D1Database;
	ASSETS: Fetcher;
	PUBLIC_RELEASE: "true";
	MAIN_ORIGIN: "http://127.0.0.1:8787";
	ARTIFACT_ORIGIN: "http://127.0.0.1:8788";
	ARTIFACT_CDN_ORIGIN: "http://127.0.0.1:8788";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/main");
	}
	interface Env extends __BaseEnv_RuntimeMainBindings {}
}
interface RuntimeMainBindings extends __BaseEnv_RuntimeMainBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_RELEASE" | "MAIN_ORIGIN" | "ARTIFACT_ORIGIN" | "ARTIFACT_CDN_ORIGIN">> {}
}
