(()=>{'use strict';
const RAW={
'first-light':['#######','#...o.#','#.....#','#..$..#','#.@...#','#.....#','#######'],
'crossfeed':['########','#..oo..#','#......#','#.$.$..#','#...@..#','#......#','########'],
'black-start':['########','#.o.o.o#','#......#','#.$.$$.#','#...@..#','#......#','########'],
'split-bus':['########','#.o..o.#','#......#','#..##..#','#.$..$.#','#...@..#','#......#','########'],
'relay-bend':['########','#..o...#','#....o.#','#..#...#','#.$.$..#','#..@...#','#......#','########'],
'service-loop':['#########','#..o.o..#','#.......#','#.#...#.#','#.$.$...#','#...@...#','#.......#','#########'],
'cold-iron':['#########','#..o..o.#','#o......#','#...#...#','#.$$.$..#','#...@...#','#.......#','#########'],
'brownout':['#########','#..ooo..#','#.......#','#..#.#..#','#.$.$.$.#','#...@...#','#.......#','#########'],
'dead-bus':['#########','#..ooo..#','#.#...#.#','#.......#','#.$$.$..#','#....@..#','#.......#','#########'],
'copper-maze':['#########','#o..o..o#','#.......#','#.#.#.#.#','#.$.$.$.#','#...@...#','#.......#','#########'],
'backfeed':['#########','#o.o....#','#...o...#','#.#...#.#','#.$.$.$.#','#..@....#','#.......#','#########'],
'load-shed':['#########','#..o.o..#','#o......#','#..##...#','#.$.$.$.#','#....@..#','#.......#','#########'],
'last-circuit':['##########','#..o.oo..#','#....o...#','#..##....#','#.$.$.$..#','#...$@...#','#........#','##########'],
'switchyard':['#########','#..oooo.#','#.......#','#.#.#...#','#.$.$.$.#','#..$@...#','#.......#','#########'],
'phase-lock':['#########','#o.o.o..#','#.......#','#..###..#','#.$...$.#','#...$@..#','#.......#','#########'],
'auxiliary':['##########','#..o.oo..#','#o.......#','#..#..#..#','#.$.$.$..#','#...$@...#','#........#','##########'],
'redline':['##########','#o.o..o.o#','#........#','#.#....#.#','#.$.$.$..#','#...$@...#','#........#','##########'],
'island-mode':['##########','#..oooo..#','#........#','#..#..#..#','#.$.$.$..#','#..$..@..#','#........#','##########'],
'cascade':['##########','#o..oo..o#','#........#','#.#.##.#.#','#.$.$.$..#','#....$@..#','#........#','##########'],
'dawn-sequence':['##########','#o..oo..o#','#...##...#','#........#','#.$.$.$..#','#...$@...#','#........#','##########']};
const IDS=Object.keys(RAW), DIR={up:[-1,0],down:[1,0],left:[0,-1],right:[0,1]}, DIR_ANGLE={up:'180deg',down:'0deg',left:'90deg',right:'-90deg'}, STORE='lumen-yard-save-v1';
const $=id=>document.getElementById(id), pos=(r,c)=>({row:r,col:c}), key=p=>p.row+','+p.col, sorted=a=>a.map(p=>pos(p.row,p.col)).sort((a,b)=>a.row-b.row||a.col-b.col), clone=o=>JSON.parse(JSON.stringify(o));
let save={complete:{},bests:{},last:'first-light',sound:true,motion:!matchMedia('(prefers-reduced-motion: reduce)').matches};try{save={...save,...JSON.parse(localStorage.getItem(STORE)||'{}')}}catch(e){}
let seed=null,state,history=[],started=false,lastDir='down',audio=null,portBinding=null,gamepadPrev=[];
function parse(id){let walls=[],goals=[],crates=[],player;RAW[id].forEach((row,r)=>[...row].forEach((ch,c)=>{if(ch==='#')walls.push(pos(r,c));if(ch==='o')goals.push(pos(r,c));if(ch==='$')crates.push(pos(r,c));if(ch==='@')player=pos(r,c)}));return{walls,goals,crates,player,width:RAW[id][0].length,height:RAW[id].length}}
function begin(id,inc=true){let b=parse(id);state={revision:state?state.revision+1:0,attempt:state?(inc?state.attempt+1:state.attempt):1,phase:'playing',outcome:null,levelId:id,...b,moveCount:0,pushCount:0};history=[];save.last=id;persist();if($('completionBackdrop'))$('completionBackdrop').hidden=true;render();return snapshot()}
function persist(){try{localStorage.setItem(STORE,JSON.stringify(save))}catch(e){}}
function occupied(p,arr){return arr.some(x=>x.row===p.row&&x.col===p.col)}
function canMove(direction){if(state.phase!=='playing'||!DIR[direction])return false;let [dr,dc]=DIR[direction],n=pos(state.player.row+dr,state.player.col+dc);if(occupied(n,state.walls))return false;if(occupied(n,state.crates)){let beyond=pos(n.row+dr,n.col+dc);return !occupied(beyond,state.walls)&&!occupied(beyond,state.crates)}return true}
function legal(){let a=[];if(state.phase==='playing')Object.keys(DIR).forEach(d=>{if(canMove(d))a.push({type:'move',direction:d})});if(history.length)a.push({type:'undo'});IDS.forEach(levelId=>{if(levelId!==state.levelId)a.push({type:'select_level',levelId})});return a}
function snapshot(){return clone({revision:state.revision,attempt:state.attempt,phase:state.phase,outcome:state.outcome,levelId:state.levelId,width:state.width,height:state.height,walls:sorted(state.walls),goals:sorted(state.goals),crates:sorted(state.crates),player:pos(state.player.row,state.player.col),poweredGoals:state.goals.filter(g=>occupied(g,state.crates)).length,moveCount:state.moveCount,pushCount:state.pushCount,undoAvailable:history.length>0,legalActions:legal()})}
function err(code,message){let e=new Error(message);e.code=code;throw e}
function sameAction(a,b){return JSON.stringify(a)===JSON.stringify(b)}
function action(input,human=false){if(!input||typeof input!=='object'||Array.isArray(input))err('INVALID_ACTION','Action must be an object.');let allowed=['move','undo','select_level'];if(!allowed.includes(input.type))err('INVALID_ACTION','Unknown action type.');let fields=Object.keys(input).sort().join(','),expected=input.type==='undo'?'type':input.type==='move'?'direction,type':'levelId,type';if(fields!==expected)err('INVALID_ACTION','Action has an invalid shape.');if(input.type==='move'&&!Object.keys(DIR).includes(input.direction))err('INVALID_ACTION','Unknown direction.');if(input.type==='select_level'&&!IDS.includes(input.levelId))err('UNKNOWN_LEVEL','Unknown board.');if(!legal().some(a=>sameAction(a,input))){if(input.type==='move'&&state.phase==='complete')err('COMPLETE','Movement is frozen after completion.');err('ILLEGAL_ACTION','That action is not legal now.')}
 if(input.type==='select_level'){begin(input.levelId);audioCue('select');return snapshot()}
 if(input.type==='undo'){let prior=history.pop(),rev=state.revision+1;state={...prior,revision:rev};lastDir='down';render('undo');audioCue('undo');return snapshot()}
 let before=clone({...state});history.push(before);let [dr,dc]=DIR[input.direction],n=pos(state.player.row+dr,state.player.col+dc),push=occupied(n,state.crates);if(push){let crate=state.crates.find(x=>key(x)===key(n));crate.row+=dr;crate.col+=dc;state.pushCount++}state.player=n;state.moveCount++;state.revision++;lastDir=input.direction;let powered=state.goals.filter(g=>occupied(g,state.crates)).length;if(powered===state.goals.length){state.phase='complete';state.outcome='powered';let old=save.bests[state.levelId];save.complete[state.levelId]=true;save.bests[state.levelId]=old==null?state.moveCount:Math.min(old,state.moveCount);persist()}render(push?'push':'move');audioCue(push?(occupied(n,state.goals)?'socket':'push'):'step');if(state.phase==='complete'){audioCue('complete');setTimeout(showCompletion,save.motion?700:50)}return snapshot()}
function rejectHuman(direction){started=true;audioCue('blocked');let wrap=$('yardWrap');wrap.classList.remove('blocked');void wrap.offsetWidth;wrap.classList.add('blocked');showToast('Path blocked')}
function render(effect){document.documentElement.style.setProperty('--motion',save.motion?1:0);$('soundButton').setAttribute('aria-pressed',save.sound);$('motionButton').setAttribute('aria-pressed',save.motion);let i=IDS.indexOf(state.levelId), powered=state.goals.filter(g=>occupied(g,state.crates)).length;
 $('boardNumber').textContent=`CIRCUIT ${String(i+1).padStart(2,'0')}`;$('boardName').textContent=state.levelId.replace(/-/g,' ');$('moves').textContent=state.moveCount;$('pushes').textContent=state.pushCount;$('power').textContent=`${powered}/${state.goals.length}`;$('undoButton').disabled=!history.length;$('bestLabel').innerHTML=`<span>BEST</span><strong>${save.bests[state.levelId]??'—'}</strong>`;$('invitation').classList.toggle('hidden',started||state.moveCount>0);
 let yard=$('yard'), wrap=$('yardWrap'), maxW=Math.min(innerWidth-24,730), available=Math.max(180,wrap.clientHeight-12), cell=Math.floor(Math.min(maxW/state.width,available/state.height,68));document.documentElement.style.setProperty('--cell',Math.max(26,cell)+'px');yard.style.gridTemplateColumns=`repeat(${state.width},var(--cell))`;yard.replaceChildren();for(let r=0;r<state.height;r++)for(let c=0;c<state.width;c++){let p=pos(r,c),w=occupied(p,state.walls),g=occupied(p,state.goals),cr=occupied(p,state.crates),pl=key(p)===key(state.player),tile=document.createElement('div');tile.className='tile '+(w?'wall':'floor')+(g?' goal':'')+(g&&cr?' powered':'');tile.dataset.row=r;tile.dataset.col=c;tile.setAttribute('role','gridcell');if(cr){let x=document.createElement('div');x.className='crate';tile.append(x)}if(pl){let x=document.createElement('div');x.className='robot';x.style.setProperty('--dir',DIR_ANGLE[lastDir]);tile.append(x)}yard.append(tile)}wrap.classList.toggle('completed',state.phase==='complete');if(effect==='undo')showToast('Current rewound');requestAnimationFrame(()=>{})}
function showCompletion(){if(state.phase!=='complete')return;let idx=IDS.indexOf(state.levelId),all=IDS.every(id=>save.complete[id]),chapter=idx===2;$('completionKicker').textContent=all?'YARD ONLINE':chapter?'GRID RESTORED':'CIRCUIT POWERED';$('completionTitle').textContent=all?'Dawn sequence complete':chapter?'Grid restored':`${state.levelId.replace(/-/g,' ')} restored`;$('completionText').textContent=all?'Twenty circuits hum beneath the waking greenhouse.':chapter?'The opening grid is alive. A deeper yard waits beyond.':idx===19?'This circuit is live. Restore the unfinished circuits to wake the whole yard.':'Current is flowing through the yard.';$('nextButton').innerHTML=all?'Replay campaign':idx===19?'Find unfinished circuits':`Next circuit <span>→</span>`;$('campaignSummary').hidden=!all;if(all){let total=IDS.reduce((n,id)=>n+(save.bests[id]||0),0);$('campaignSummary').innerHTML=`<span>20/20<small>RESTORED</small></span><span>${total}<small>BEST MOVES</small></span>`}$('completionBackdrop').hidden=false;$('nextButton').focus()}
function closeCompletion(){$('completionBackdrop').hidden=true}
function openMap(){closeCompletion();renderMap();$('drawerBackdrop').hidden=false;$('closeMap').focus()}
function renderMap(){let n=IDS.filter(id=>save.complete[id]).length;$('progressText').textContent=`${n} / 20 restored`;$('progressBar').firstElementChild.style.width=n/20*100+'%';let grid=$('levelGrid');grid.replaceChildren();IDS.forEach((id,i)=>{let b=document.createElement('button');b.className='level-button'+(id===state.levelId?' current':'')+(save.complete[id]?' complete':'');b.innerHTML=`<b>${String(i+1).padStart(2,'0')} · ${id.replace(/-/g,' ')}</b><small>${save.bests[id]!=null?'BEST '+save.bests[id]+' MOVES':'UNRESTORED'}</small>`;b.onclick=()=>{action({type:'select_level',levelId:id},true);$('drawerBackdrop').hidden=true};grid.append(b)})}
function showToast(t){let x=$('toast');x.textContent=t;x.classList.add('show');clearTimeout(x._t);x._t=setTimeout(()=>x.classList.remove('show'),900)}
function ensureAudio(){if(!save.sound)return null;if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();return audio}
function audioCue(type){let a=ensureAudio();if(!a)return;let map={step:[180,.035,.04],push:[82,.11,.12],blocked:[55,.05,.08],undo:[310,.12,.06],socket:[540,.14,.1],complete:[120,.8,.13],select:[260,.05,.04]},v=map[type]||map.step,o=a.createOscillator(),g=a.createGain();o.type=type==='push'||type==='blocked'?'square':'sine';o.frequency.setValueAtTime(v[0],a.currentTime);if(type==='complete')o.frequency.exponentialRampToValueAtTime(760,a.currentTime+v[1]);if(type==='undo')o.frequency.exponentialRampToValueAtTime(130,a.currentTime+v[1]);g.gain.setValueAtTime(v[2],a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+v[1]);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+v[1])}
function humanMove(d){started=true;if(canMove(d))action({type:'move',direction:d},true);else rejectHuman(d)}
function restart(){return begin(state.levelId)}
function apiReset(s){seed=s;state=null;started=false;return begin('first-light',false)}
window.__ARENA_GAME__={reset:apiReset,snapshot,act:a=>action(a),restart};
function bridgeResponse(req,accepted,error){let env={protocol:'arena.game.v1',type:'response',requestId:req.requestId,sessionId:portBinding.sessionId,generation:portBinding.generation,accepted,revision:state.revision,state:snapshot()};if(error)env.error=error;portBinding.port.postMessage(env)}
addEventListener('message',e=>{let m=e.data;if(e.source!==parent||!m||m.protocol!=='arena.game.v1'||m.type!=='connect'||typeof m.sessionId!=='string'||!Number.isInteger(m.generation)||!e.ports[0])return;if(portBinding)portBinding.port.close();portBinding={port:e.ports[0],sessionId:m.sessionId,generation:m.generation,seen:new Set()};let p=portBinding.port;p.onmessage=ev=>{let q=ev.data;if(!q||q.protocol!=='arena.game.v1'||q.sessionId!==portBinding.sessionId||q.generation!==portBinding.generation)return;try{if(portBinding.seen.has(q.requestId))err('DUPLICATE_REQUEST','Request was already handled.');portBinding.seen.add(q.requestId);if(!['observe','act','restart'].includes(q.command))err('UNKNOWN_COMMAND','Unknown command.');if(q.command!=='observe'&&q.expectedRevision!==state.revision)err('STALE_REVISION','Expected revision does not match.');if(q.command==='act')action(q.action);else if(q.command==='restart')restart();bridgeResponse(q,true)}catch(e){bridgeResponse(q,false,{code:e.code||'ERROR',message:e.message||'Request rejected.'})}};p.start();p.postMessage({protocol:'arena.game.v1',type:'ready',sessionId:m.sessionId,generation:m.generation,accepted:true,revision:state.revision,state:snapshot()})});
$('undoButton').onclick=()=>{started=true;try{action({type:'undo'},true)}catch(e){}};$('restartButton').onclick=()=>{started=true;restart();audioCue('select')};$('mapButton').onclick=openMap;$('completionMapButton').onclick=openMap;$('closeMap').onclick=()=>$('drawerBackdrop').hidden=true;$('drawerBackdrop').onclick=e=>{if(e.target===$('drawerBackdrop'))$('drawerBackdrop').hidden=true};$('replayButton').onclick=()=>{closeCompletion();restart()};$('nextButton').onclick=()=>{let idx=IDS.indexOf(state.levelId),all=IDS.every(id=>save.complete[id]);closeCompletion();if(all)begin('first-light');else if(idx<IDS.length-1)begin(IDS[idx+1]);else openMap()};$('soundButton').onclick=()=>{save.sound=!save.sound;persist();render();if(save.sound)audioCue('select')};$('motionButton').onclick=()=>{save.motion=!save.motion;persist();render()};$('completionBackdrop').onclick=e=>{if(e.target===$('completionBackdrop'))closeCompletion()};
addEventListener('keydown',e=>{if(!$('drawerBackdrop').hidden||!$('completionBackdrop').hidden)return;let d={ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right'}[e.key];if(d){e.preventDefault();humanMove(d)}else if(['u','U','Backspace'].includes(e.key)){e.preventDefault();if(history.length)action({type:'undo'},true)}else if(e.key==='r'||e.key==='R'){restart()}});
let touch=null;$('yard').addEventListener('pointerdown',e=>{touch={x:e.clientX,y:e.clientY};$('yard').setPointerCapture(e.pointerId)});$('yard').addEventListener('pointerup',e=>{if(!touch)return;let dx=e.clientX-touch.x,dy=e.clientY-touch.y,d;if(Math.hypot(dx,dy)>24)d=Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up');else{let tile=e.target.closest('.tile');if(tile){let dr=+tile.dataset.row-state.player.row,dc=+tile.dataset.col-state.player.col;if(Math.abs(dr)+Math.abs(dc)===1)d=dr<0?'up':dr>0?'down':dc<0?'left':'right'}}touch=null;if(d)humanMove(d)});
function gamepadLoop(){let gp=navigator.getGamepads?.()[0];if(gp){let now=[gp.buttons[12]?.pressed||gp.axes[1]<-.6,gp.buttons[13]?.pressed||gp.axes[1]>.6,gp.buttons[14]?.pressed||gp.axes[0]<-.6,gp.buttons[15]?.pressed||gp.axes[0]>.6,gp.buttons[1]?.pressed,gp.buttons[9]?.pressed];['up','down','left','right'].forEach((d,i)=>{if(now[i]&&!gamepadPrev[i])humanMove(d)});if(now[4]&&!gamepadPrev[4]&&history.length)action({type:'undo'},true);if(now[5]&&!gamepadPrev[5])restart();gamepadPrev=now}requestAnimationFrame(gamepadLoop)}
addEventListener('resize',()=>render());begin(save.last&&IDS.includes(save.last)?save.last:'first-light',false);requestAnimationFrame(gamepadLoop);
})();