/* Lumen Yard — the twenty authored boards. Each is a fixed level. */
(function (root) {
  'use strict';

  var LEVELS = {
    'first-light': [
      '#######',
      '#...o.#',
      '#.....#',
      '#..$..#',
      '#.@...#',
      '#.....#',
      '#######',
    ],
    'crossfeed': [
      '########',
      '#..oo..#',
      '#......#',
      '#.$.$..#',
      '#...@..#',
      '#......#',
      '########',
    ],
    'black-start': [
      '########',
      '#.o.o.o#',
      '#......#',
      '#.$.$$.#',
      '#...@..#',
      '#......#',
      '########',
    ],
    'split-bus': [
      '########',
      '#.o..o.#',
      '#......#',
      '#..##..#',
      '#.$..$.#',
      '#...@..#',
      '#......#',
      '########',
    ],
    'relay-bend': [
      '########',
      '#..o...#',
      '#....o.#',
      '#..#...#',
      '#.$.$..#',
      '#..@...#',
      '#......#',
      '########',
    ],
    'service-loop': [
      '#########',
      '#..o.o..#',
      '#.......#',
      '#.#...#.#',
      '#.$.$...#',
      '#...@...#',
      '#.......#',
      '#########',
    ],
    'cold-iron': [
      '#########',
      '#..o..o.#',
      '#o......#',
      '#...#...#',
      '#.$$.$..#',
      '#...@...#',
      '#.......#',
      '#########',
    ],
    'brownout': [
      '#########',
      '#..ooo..#',
      '#.......#',
      '#..#.#..#',
      '#.$.$.$.#',
      '#...@...#',
      '#.......#',
      '#########',
    ],
    'dead-bus': [
      '#########',
      '#..ooo..#',
      '#.#...#.#',
      '#.......#',
      '#.$$.$..#',
      '#....@..#',
      '#.......#',
      '#########',
    ],
    'copper-maze': [
      '#########',
      '#o..o..o#',
      '#.......#',
      '#.#.#.#.#',
      '#.$.$.$.#',
      '#...@...#',
      '#.......#',
      '#########',
    ],
    'backfeed': [
      '#########',
      '#o.o....#',
      '#...o...#',
      '#.#...#.#',
      '#.$.$.$.#',
      '#..@....#',
      '#.......#',
      '#########',
    ],
    'load-shed': [
      '#########',
      '#..o.o..#',
      '#o......#',
      '#..##...#',
      '#.$.$.$.#',
      '#....@..#',
      '#.......#',
      '#########',
    ],
    'last-circuit': [
      '##########',
      '#..o.oo..#',
      '#....o...#',
      '#..##....#',
      '#.$.$.$..#',
      '#...$@...#',
      '#........#',
      '##########',
    ],
    'switchyard': [
      '#########',
      '#..oooo.#',
      '#.......#',
      '#.#.#...#',
      '#.$.$.$.#',
      '#..$@...#',
      '#.......#',
      '#########',
    ],
    'phase-lock': [
      '#########',
      '#o.o.o..#',
      '#.......#',
      '#..###..#',
      '#.$...$.#',
      '#...$@..#',
      '#.......#',
      '#########',
    ],
    'auxiliary': [
      '##########',
      '#..o.oo..#',
      '#o.......#',
      '#..#..#..#',
      '#.$.$.$..#',
      '#...$@...#',
      '#........#',
      '##########',
    ],
    'redline': [
      '##########',
      '#o.o..o.o#',
      '#........#',
      '#.#....#.#',
      '#.$.$.$..#',
      '#...$@...#',
      '#........#',
      '##########',
    ],
    'island-mode': [
      '##########',
      '#..oooo..#',
      '#........#',
      '#..#..#..#',
      '#.$.$.$..#',
      '#..$..@..#',
      '#........#',
      '##########',
    ],
    'cascade': [
      '##########',
      '#o..oo..o#',
      '#........#',
      '#.#.##.#.#',
      '#.$.$.$..#',
      '#....$@..#',
      '#........#',
      '##########',
    ],
    'dawn-sequence': [
      '##########',
      '#o..oo..o#',
      '#...##...#',
      '#........#',
      '#.$.$.$..#',
      '#...$@...#',
      '#........#',
      '##########',
    ],
  };

  var LEVEL_ORDER = [
    'first-light',
    'crossfeed',
    'black-start',
    'split-bus',
    'relay-bend',
    'service-loop',
    'cold-iron',
    'brownout',
    'dead-bus',
    'copper-maze',
    'backfeed',
    'load-shed',
    'last-circuit',
    'switchyard',
    'phase-lock',
    'auxiliary',
    'redline',
    'island-mode',
    'cascade',
    'dawn-sequence',
  ];

  var LEVEL_META = {
    'first-light': { name: 'First Light', short: 'First', chapter: 1 },
    'crossfeed': { name: 'Crossfeed', short: 'Cross', chapter: 1 },
    'black-start': { name: 'Black Start', short: 'Black', chapter: 1 },
    'split-bus': { name: 'Split Bus', short: 'Split', chapter: 2 },
    'relay-bend': { name: 'Relay Bend', short: 'Bend', chapter: 2 },
    'service-loop': { name: 'Service Loop', short: 'Loop', chapter: 2 },
    'cold-iron': { name: 'Cold Iron', short: 'Iron', chapter: 2 },
    'brownout': { name: 'Brownout', short: 'Brown', chapter: 2 },
    'dead-bus': { name: 'Dead Bus', short: 'Dead', chapter: 2 },
    'copper-maze': { name: 'Copper Maze', short: 'Maze', chapter: 2 },
    'backfeed': { name: 'Backfeed', short: 'Feed', chapter: 3 },
    'load-shed': { name: 'Load Shed', short: 'Shed', chapter: 3 },
    'last-circuit': { name: 'Last Circuit', short: 'Last', chapter: 3 },
    'switchyard': { name: 'Switchyard', short: 'Yard', chapter: 3 },
    'phase-lock': { name: 'Phase Lock', short: 'Phase', chapter: 3 },
    'auxiliary': { name: 'Auxiliary', short: 'Aux', chapter: 3 },
    'redline': { name: 'Redline', short: 'Red', chapter: 3 },
    'island-mode': { name: 'Island Mode', short: 'Island', chapter: 3 },
    'cascade': { name: 'Cascade', short: 'Cascade', chapter: 3 },
    'dawn-sequence': { name: 'Dawn Sequence', short: 'Dawn', chapter: 4 },
  };

  root.Lumen = root.Lumen || {};
  root.Lumen.LEVELS = LEVELS;
  root.Lumen.LEVEL_ORDER = LEVEL_ORDER;
  root.Lumen.LEVEL_META = LEVEL_META;
})(typeof window !== 'undefined' ? window : globalThis);
