(()=>{'use strict';
const STEP=1000/60, RANKS=['DRIFT','SHELL','CURRENT','MOON','HIGH TIDE'], EVENT_LIMIT=240;
const $=s=>document.querySelector(s), boardEl=$('#board'), gameEl=$('#game'), ceremony=$('#ceremony');
const ui={pearls:$('#pearls'),pool:$('#poolLabel'),tide:$('#tideFill'),tideText:$('#tideText'),left:$('#left'),hint:$('#hint'),host:$('#host'),toast:$('#toast'),rank:$('#rank'),final:$('#finalPearls'),best:$('#best'),deepest:$('#deepest'),title:$('#resultTitle'),sound:$('#sound')};
let state, mines=null, nums=null, opened=null, flags=null, eventSeq=0, sessionBest=0, attempt=0, seedValue='shoal', accumulator=0, lastFrame=performance.now(), audio=null, muted=false, clearTimer=0, nextAmbience=0;
const hash=str=>{let h=2166136261>>>0;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}h+=h<<13;h^=h>>>7;h+=h<<3;h^=h>>>17;h+=h<<5;return h>>>0};
const rngFrom=s=>{let a=hash(s)||1;return()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}};
function spec(pool){if(pool===1)return[6,6,5];if(pool===2)return[7,7,8];if(pool===3)return[7,8,11];return[8,Math.min(10,8+Math.floor((pool-4)/2)),Math.min(19,13+pool-4)]}
const idx=(x,y)=>y*state.gridWidth+x, inside=(x,y)=>x>=0&&y>=0&&x<state.gridWidth&&y<state.gridHeight;
function near(i){const x=i%state.gridWidth,y=Math.floor(i/state.gridWidth),a=[];for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++)if((dx||dy)&&inside(x+dx,y+dy))a.push(idx(x+dx,y+dy));return a}
function numbersFor(m){return m.map((_,i)=>near(i).reduce((n,j)=>n+(m[j]?1:0),0))}
function flood(start,m,n,seen,blocked){const q=[start];while(q.length){const i=q.shift();if(seen[i]||blocked[i]||m[i])continue;seen[i]=1;if(n[i]===0)near(i).forEach(j=>{if(!seen[j]&&!m[j]&&!blocked[j])q.push(j)})}}
function basicSolvable(m,n,first){const seen=m.map(()=>0), known=m.map(()=>0), blocked=m.map(()=>0);flood(first,m,n,seen,blocked);let progress=true;while(progress){progress=false;for(let i=0;i<m.length;i++)if(seen[i]){const ns=near(i), ks=ns.filter(j=>known[j]).length, unknown=ns.filter(j=>!seen[j]&&!known[j]);if(unknown.length&&n[i]-ks===unknown.length){unknown.forEach(j=>known[j]=1);progress=true}if(unknown.length&&n[i]===ks){unknown.forEach(j=>flood(j,m,n,seen,blocked));progress=true}}
const unknown=m.map((_,i)=>i).filter(i=>!seen[i]&&!known[i]);const remaining=m.reduce((a,v)=>a+v,0)-known.reduce((a,v)=>a+v,0);if(unknown.length&&remaining===0){unknown.forEach(j=>flood(j,m,n,seen,blocked));progress=true}else if(unknown.length&&remaining===unknown.length){unknown.forEach(j=>known[j]=1);progress=true}}
return m.every((v,i)=>v?known[i]:seen[i])}
function generate(first){const total=state.gridWidth*state.gridHeight, forbidden=new Set([first,...near(first)]), spots=[];for(let i=0;i<total;i++)if(!forbidden.has(i))spots.push(i);const base=`${state.seed}|${state.pool}|${first}`;for(let pass=0;;pass++){const r=rngFrom(`${base}|${pass}`), order=spots.slice();for(let i=order.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[order[i],order[j]]=[order[j],order[i]]}const m=Array(total).fill(false);order.slice(0,state.urchinsTotal).forEach(i=>m[i]=true);const n=numbersFor(m);if(basicSolvable(m,n,first))return[m,n]}}
function blankPool(pool){const [w,h,u]=spec(pool);state.pool=pool;state.gridWidth=w;state.gridHeight=h;state.urchinsTotal=u;state.flagsPlaced=0;state.urchinsLeft=u;state.tideFraction=1;state.firstTurnDone=false;state.stungAt=null;state.poolTick=0;state.poolDurationTicks=Math.round((54+pool*5)*60);mines=nums=null;opened=Array(w*h).fill(false);flags=Array(w*h).fill(false);accumulator=0}
function reset(seed){seedValue=String(seed??'shoal');attempt++;eventSeq=0;clearTimeout(clearTimer);state={phase:'ready',tick:0,elapsedMs:0,seed:seedValue,attempt,revision:0,pool:1,pearls:0,sessionBest,moves:0,rank:null,rankLadder:RANKS.slice(),events:[],lastEvent:null,biggestRipple:0};blankPool(1);render();return snapshot()}
function restart(){return reset(seedValue)}
function addEvent(kind,extra={}){const e={seq:++eventSeq,kind,tick:state.tick,...extra};state.events.push(e);if(state.events.length>EVENT_LIMIT)state.events.splice(0,state.events.length-EVENT_LIMIT);state.lastEvent=e}
function startPool(first){[mines,nums]=generate(first);state.firstTurnDone=true;if(state.phase==='ready')state.phase='playing'}
function openOne(i,changed){if(opened[i]||flags[i])return;if(mines[i]){changed.stung=true;changed.fatal=i;return}const prior=opened.slice(),before=opened.reduce((a,v)=>a+(v?1:0),0);flood(i,mines,nums,opened,flags);const after=opened.reduce((a,v)=>a+(v?1:0),0);changed.opened+=after-before;for(let j=0;j<opened.length;j++)if(opened[j]&&!prior[j])changed.newly.push(j)}
function checkClear(){if(state.phase==='ended'||!mines)return false;for(let i=0;i<mines.length;i++)if(!mines[i]&&!opened[i])return false;const cleared=state.pool,bonus=Math.round((25+cleared*20)*state.tideFraction);state.pearls+=bonus;addEvent('pool_clear',{pool:cleared});state.biggestRipple=Math.max(state.biggestRipple,0);blankPool(cleared+1);state.phase='playing';showToast(`POOL ${String(cleared).padStart(2,'0')} CLEAR`);hostMood('cheer');sound('clear');clearTimer=setTimeout(()=>{if(state.phase!=='ended')hostMood('curious')},1250);return true}
function sting(i){state.phase='ended';state.stungAt={x:i%state.gridWidth,y:Math.floor(i/state.gridWidth)};addEvent('sting');state.rank=rankFor(state.pearls);sessionBest=Math.max(sessionBest,state.pearls);state.sessionBest=sessionBest;addEvent('run_end');sound('sting');gameEl.classList.remove('shake');void gameEl.offsetWidth;gameEl.classList.add('shake');hostMood('stung')}
function rankFor(p){return RANKS[p>=900?4:p>=470?3:p>=210?2:p>=70?1:0]}
function perform(a){if(!a||typeof a!=='object'||state.phase==='ended')return{ok:false,error:'illegal_action'};const x=a.x,y=a.y;if(!Number.isInteger(x)||!Number.isInteger(y)||!inside(x,y))return{ok:false,error:'illegal_action'};const i=idx(x,y), changed={opened:0,stung:false,newly:[],origin:i};if(a.type==='open'){
if(opened[i]||flags[i])return{ok:false,error:'illegal_action'};if(!state.firstTurnDone)startPool(i);openOne(i,changed);state.moves++;state.pearls+=changed.opened;state.biggestRipple=Math.max(state.biggestRipple,changed.opened);addEvent('open',{opened:changed.opened});if(changed.stung)sting(changed.fatal);else sound(changed.opened>1?'ripple':'open',changed.opened)}else if(a.type==='flag'){if(opened[i]||flags[i])return{ok:false,error:'illegal_action'};flags[i]=true;state.flagsPlaced++;state.urchinsLeft--;state.moves++;addEvent('flag');sound('flag')}else if(a.type==='unflag'){if(!flags[i]||state.phase==='ended')return{ok:false,error:'illegal_action'};flags[i]=false;state.flagsPlaced--;state.urchinsLeft++;state.moves++;addEvent('unflag');sound('flag')}else if(a.type==='sweep'){
if(!opened[i])return{ok:false,error:'illegal_action'};const ns=near(i),count=ns.filter(j=>flags[j]).length;if(count!==nums[i])return{ok:false,error:'illegal_action'};for(const j of ns)if(!opened[j]&&!flags[j]&&!changed.stung)openOne(j,changed);state.moves++;state.pearls+=changed.opened;state.biggestRipple=Math.max(state.biggestRipple,changed.opened);addEvent('sweep',{opened:changed.opened});if(changed.stung)sting(changed.fatal);else sound('sweep',changed.opened)}else return{ok:false,error:'illegal_action'};
state.revision++;const advanced=!changed.stung&&checkClear();render(advanced?0:changed.opened,advanced?[]:changed.newly,changed.origin);return{ok:true,state:snapshot()}}
function act(a){return perform(a).state||snapshot()}
function advance(ms){if(!Number.isFinite(ms)||ms<=0)return snapshot();if(state.phase!=='playing'||!state.firstTurnDone)return snapshot();accumulator+=ms;const steps=Math.floor((accumulator+1e-9)/STEP);accumulator-=steps*STEP;if(steps){state.tick+=steps;state.elapsedMs=Math.round(state.tick*STEP*1000)/1000;state.poolTick+=steps;state.tideFraction=Math.max(0,1-state.poolTick/state.poolDurationTicks);renderHud()}return snapshot()}
function rows(){const out=[];for(let y=0;y<state.gridHeight;y++){let row='';for(let x=0;x<state.gridWidth;x++){const i=idx(x,y);if(state.phase==='ended'){if(state.stungAt&&i===idx(state.stungAt.x,state.stungAt.y))row+='X';else if(flags[i])row+=mines[i]?'+':'-';else if(mines[i])row+='*';else if(opened[i])row+=String(nums[i]);else row+='#'}else if(flags[i])row+='F';else if(opened[i])row+=String(nums[i]);else row+='#'}out.push(row)}return out}
function snapshot(){const s={phase:state.phase,tick:state.tick,elapsedMs:state.elapsedMs,seed:state.seed,attempt:state.attempt,revision:state.revision,pool:state.pool,pearls:state.pearls,sessionBest:state.sessionBest,moves:state.moves,rank:state.rank,rankLadder:state.rankLadder.slice(),gridWidth:state.gridWidth,gridHeight:state.gridHeight,urchinsTotal:state.urchinsTotal,flagsPlaced:state.flagsPlaced,urchinsLeft:state.urchinsLeft,tideFraction:state.tideFraction,firstTurnDone:state.firstTurnDone,stungAt:state.stungAt?{...state.stungAt}:null,rows:rows(),events:state.events.map(e=>({...e})),lastEvent:state.lastEvent?{...state.lastEvent}:null};return Object.freeze(s)}
function bridgeState(){const {events,lastEvent,...visible}=snapshot();return visible}
function render(openCount=0,newly=[],origin=0){boardEl.style.setProperty('--cols',state.gridWidth);boardEl.style.setProperty('--rows',state.gridHeight);const visible=rows(),fresh=new Set(newly),ox=origin%state.gridWidth,oy=Math.floor(origin/state.gridWidth);boardEl.innerHTML='';for(let y=0;y<state.gridHeight;y++)for(let x=0;x<state.gridWidth;x++){const c=visible[y][x],b=document.createElement('button'),i=idx(x,y);b.className='cell';b.dataset.x=x;b.dataset.y=y;b.setAttribute('role','gridcell');if(c==='#'){b.classList.add('covered');b.innerHTML='<i class="shell"></i>';b.setAttribute('aria-label','Covered shell')}else if(c==='F'){b.classList.add('covered','flagged');b.innerHTML='<i class="shell"></i><i class="flag-mark"></i>';b.setAttribute('aria-label','Pennanted shell')}else if(/[0-8]/.test(c)){b.classList.add('open',`n${c}`);if(fresh.has(i)){b.classList.add('fresh');b.style.setProperty('--delay',`${Math.min(180,(Math.abs(x-ox)+Math.abs(y-oy))*28)}ms`)}b.innerHTML=`<span class="num">${c}</span>`;b.setAttribute('aria-label',`${c} neighboring urchins`)}else{b.classList.add('covered','reveal');if(c==='X')b.classList.add('fatal');if(c==='-'||c==='+')b.classList.add('flagged');if(c==='-')b.classList.add('wrong');b.innerHTML='<i class="shell"></i>'+((c==='-'||c==='+')?'<i class="flag-mark"></i>':'');b.setAttribute('aria-label',c==='X'?'Fatal urchin':c==='-'?'Wrong pennant':c==='+'?'Correct pennant':'Urchin')};boardEl.appendChild(b)}renderHud();if(openCount>1)spawnRing();if(state.phase==='ended')setTimeout(showCeremony,520);else{ceremony.classList.remove('show');ceremony.setAttribute('aria-hidden','true')}}
function renderHud(){ui.pearls.textContent=state.pearls;ui.pool.textContent=`POOL ${String(state.pool).padStart(2,'0')}`;ui.left.textContent=state.urchinsLeft;ui.tide.style.transform=`scaleX(${state.tideFraction})`;ui.tideText.textContent=!state.firstTurnDone?'WAITING':state.tideFraction<=0?'LOW WATER':`${Math.ceil(state.tideFraction*100)}%`;ui.hint.textContent=!state.firstTurnDone&&state.pool===1?'TAP A SHELL TO BEGIN':state.flagsPlaced===0?'HOLD TO PLANT A PENNANT':'TAP A SATISFIED NUMBER TO SWEEP';if(state.phase==='playing'&&state.firstTurnDone){const safeLeft=opened.filter((v,i)=>!v&&!mines[i]).length;if(safeLeft<=5)hostMood('worried')} }
function showCeremony(){if(state.phase!=='ended')return;ui.rank.textContent=state.rank;ui.final.textContent=state.pearls;ui.best.textContent=state.sessionBest;ui.deepest.textContent=state.pool;ui.title.textContent=state.pearls===state.sessionBest&&state.pearls>0?'A NEW MARK IN THE SAND':'A SHARP LESSON';ceremony.classList.add('show');ceremony.setAttribute('aria-hidden','false');sound('ceremony')}
function hostMood(m){ui.host.className=`host ${m}`}
function showToast(t){ui.toast.textContent=t;ui.toast.classList.remove('show');void ui.toast.offsetWidth;ui.toast.classList.add('show')}
function spawnRing(){const r=document.createElement('i');r.className='ring';r.style.left=`${35+Math.random()*30}%`;r.style.top=`${35+Math.random()*30}%`;$('#rippleLayer').appendChild(r);setTimeout(()=>r.remove(),700)}
function ensureAudio(){if(!audio)try{audio=new (window.AudioContext||window.webkitAudioContext)();nextAmbience=audio.currentTime+.4}catch{}if(audio&&audio.state==='suspended')audio.resume()}
function tone(freq,dur=.08,type='sine',vol=.035,delay=0){if(!audio||muted)return;const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(vol,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g).connect(audio.destination);o.start(t);o.stop(t+dur+.02)}
function sound(k,n=1){if(!audio||muted)return;if(k==='open')tone(420,.07,'sine');if(k==='flag'){tone(760,.05,'triangle');tone(1040,.06,'triangle',.025,.045)}if(k==='ripple')for(let i=0;i<Math.min(n,9);i++)tone(350+i*45,.16,'sine',.022,i*.035);if(k==='sweep')for(let i=0;i<5;i++)tone(500+i*80,.12,'triangle',.025,i*.025);if(k==='sting'){tone(150,.5,'sawtooth',.07);tone(92,.7,'square',.035,.08)}if(k==='clear')for(let i=0;i<4;i++)tone([440,554,659,880][i],.4,'sine',.04,i*.09);if(k==='ceremony')tone(330,.7,'sine',.025)}
let press=null;
boardEl.addEventListener('pointerdown',e=>{if(state.phase==='ended'||e.button!==0)return;ensureAudio();const cell=e.target.closest('.cell');if(!cell)return;e.preventDefault();cell.setPointerCapture(e.pointerId);cell.classList.add('pressed');const x=+cell.dataset.x,y=+cell.dataset.y,startX=e.clientX,startY=e.clientY;press={cell,x,y,id:e.pointerId,moved:false,held:false,startX,startY,timer:setTimeout(()=>{if(!press||press.moved)return;press.held=true;const i=idx(x,y);perform({type:flags[i]?'unflag':'flag',x,y});navigator.vibrate?.(18)},480)}});
boardEl.addEventListener('pointermove',e=>{if(press&&Math.hypot(e.clientX-press.startX,e.clientY-press.startY)>12){press.moved=true;clearTimeout(press.timer);press.cell.classList.remove('pressed')}});
boardEl.addEventListener('pointerup',e=>{if(!press||e.pointerId!==press.id)return;clearTimeout(press.timer);press.cell.classList.remove('pressed');if(!press.moved&&!press.held){const i=idx(press.x,press.y);perform({type:opened[i]?'sweep':'open',x:press.x,y:press.y})}press=null});
boardEl.addEventListener('pointercancel',()=>{if(press){clearTimeout(press.timer);press.cell.classList.remove('pressed');press=null}});
boardEl.addEventListener('contextmenu',e=>{e.preventDefault();ensureAudio();const c=e.target.closest('.cell');if(!c||state.phase==='ended')return;const x=+c.dataset.x,y=+c.dataset.y,i=idx(x,y);perform({type:flags[i]?'unflag':'flag',x,y})});
ceremony.addEventListener('click',()=>{ensureAudio();restart()});ui.sound.addEventListener('click',e=>{e.stopPropagation();ensureAudio();muted=!muted;ui.sound.classList.toggle('muted',muted)});window.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='r')restart()});
function frame(now){const dt=Math.min(100,now-lastFrame);lastFrame=now;if(state?.phase==='playing'&&state.firstTurnDone)advance(dt);if(audio&&!muted&&state?.phase!=='ended'&&audio.currentTime>=nextAmbience){const low=state.firstTurnDone&&state.tideFraction<.18;tone(low?145:210,low?.7:1.15,'sine',low?.009:.006);tone(low?218:315,low?.5:.9,'sine',.004,.14);nextAmbience=audio.currentTime+(low?2.4:4.8)}requestAnimationFrame(frame)}
window.__ARENA_GAME__={reset,snapshot,act,restart,advance};
window.addEventListener('message',e=>{
  const d=e.data;
  if(e.source!==window.parent||!d||d.protocol!=='arena.game.v1'||d.type!=='connect'||typeof d.sessionId!=='string'||!Number.isInteger(d.generation)||!e.ports?.[0])return;
  const port=e.ports[0],sessionId=d.sessionId,generation=d.generation;
  port.onmessage=ev=>{
    const q=ev.data;
    if(!q||q.protocol!=='arena.game.v1'||q.sessionId!==sessionId||q.generation!==generation)return;
    let accepted=false,error=null;
    if(q.command==='observe') accepted=true;
    else if(q.command==='act'||q.command==='restart'){
      if(!Number.isInteger(q.expectedRevision)||q.expectedRevision!==state.revision) error={code:'stale_revision',message:'Expected revision does not match'};
      else if(q.command==='restart'){restart();accepted=true}
      else{const result=perform(q.action);accepted=result.ok;if(!accepted)error={code:'illegal_action',message:'Action is not legal in the current state'}}
    }else error={code:'bad_command',message:'Unknown command'};
    requestAnimationFrame(()=>port.postMessage({protocol:'arena.game.v1',type:'response',requestId:q.requestId,sessionId,generation,accepted,revision:state.revision,state:bridgeState(),...(error?{error}:{})}));
  };
  port.start();
  port.postMessage({protocol:'arena.game.v1',type:'ready',sessionId,generation,accepted:true,revision:state.revision,state:bridgeState()});
});
reset('shoal');requestAnimationFrame(frame);
})();
